openapi: "3.0.1"
info:
  title: "awscodestar-beta-infrastructure"
  version: "1.0"
paths:
  /login:
    get:
      parameters:
      - name: "id_token"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content: {}
      x-amazon-apigateway-request-validator: "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "https://steven-sg.com"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.header.Authorization: "method.request.querystring.id_token"
        passthroughBehavior: "when_no_match"
        type: "http_proxy"
  /:
    get:
      responses:
        "200":
          description: "200 response"
          content: {}
      security:
      - DefaultCognitoAuthorizer: []
components:
  securitySchemes:
    DefaultCognitoAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        providerARNs:
        - "arn:aws:cognito-idp:eu-west-1:701812189816:userpool/eu-west-1_ma0c2uawc"
        type: "cognito_user_pools"
x-amazon-apigateway-request-validators:
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false
