openapi: "3.0.1"
info:
  title: "awscodestar-beta-infrastructure"
  version: "1.0"
paths:
  /login:
    post:
      responses:
        "200":
          description: "200 response"
          content: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:701812189816:function:awscodestar-beta-lambda-GetHelloWorld:live/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /:
    get:
      responses:
        "200":
          description: "200 response"
          content: {}
      security:
        - DefaultCognitoAuthorizer: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:701812189816:function:awscodestar-beta-lambda-GetHelloWorld:live/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
components:
  securitySchemes:
    DefaultCognitoAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        providerARNs:
          - "arn:aws:cognito-idp:eu-west-1:701812189816:userpool/eu-west-1_ma0c2uawc"
        type: "cognito_user_pools"
